---
# task file for glusterfs-kubernetes (cns/ocs? name changes every month)

# Pre-reqs. Currently testing deployments manually and will add automation later
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-client
    - iptables-persistent

# I should make this something idempotent later.
- name: copy over rules
  copy:
    src: files/rules.v4
    dest: /etc/iptables/rules.v4

- name: load rules
  shell: netfilter-persistent reload

- name: load kernel modules
  shell: "modprobe {{ item }}"
  with_items:
    - dm_snapshot
    - dm_mirror
    - dm_thin_pool

- name: load modules at boot
  shell: "echo {{ item }} > /etc/modules-load.d/{{ item }}.conf"
  with_items:
    - dm_snapshot
    - dm_mirror
    - dm_thin_pool

#TODO: Add a way to parse topology.json and clean the filesystems of blocks before deployments
#TODO add check for topology.json

- name: copy over gluster-kubernetes deployment files
  synchronize:
    src: files/deploy/
    dest: /tmp/deploy/

- name: deploy glusterfs-kubernetes
  shell: /tmp/gk-deploy -gvy topology.json
  ignore_errors: true #I'm probably going to need with_items
